# Generated by Django 5.1.7 on 2025-03-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('google_map_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('youtupe', models.URLField(blank=True, null=True)),
                ('whatshapp', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shop_name', models.TextField(default='noob', max_length=200)),
                ('profile_image_url', models.URLField()),
                ('mobile_number', models.IntegerField()),
                ('slogan', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(default='noob', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Models.address')),
                ('socialMedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Models.socialmedia')),
            ],
        ),
    ]
