# Generated by Django 5.1.7 on 2025-03-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Country',
            new_name='country',
        ),
    ]
