# Generated by Django 5.1.7 on 2025-03-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_rename_country_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
