# Generated by Django 5.1.7 on 2025-03-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_profile_address_alter_profile_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Models.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socialMedia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Models.socialmedia'),
        ),
    ]
