# Generated by Django 5.1.7 on 2025-03-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_alter_profile_address_alter_profile_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_profile', to='Models.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(default='noob', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socialMedia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to='Models.socialmedia'),
        ),
    ]
