# Generated by Django 5.1.7 on 2025-04-21 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_posts_thumbnail_url_alter_posts_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
