# Generated by Django 5.1.7 on 2025-04-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prize',
            new_name='product_prize',
        ),
    ]
